- job:
    name: ceilometermiddleware-integration
    parent: telemetry-dsvm-integration
    required-projects:
      - openstack/ceilometermiddleware

- project:
    templates:
      - openstack-python3-zed-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - ceilometermiddleware-integration
    gate:
      jobs:
        - ceilometermiddleware-integration
